### ISSUE TITLE
Support for phpstan 2?

### ISSUE THREAD

**Issue by mfn** [thecodingmachine/phpstan-strict-rules#66]
phpstan 2.0 was just released:
- https://github.com/phpstan/phpstan/releases/tag/2.0.0
- https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants
- Upgrade guide: https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md

**Comment by extern-kovalenko** [comment]
So update will be or not?

**Comment by fabianblum** [comment]
I tested it with phpstan ^2. It seems to work with the current version https://github.com/thecodingmachine/phpstan-strict-rules/pull/67

**Comment by extern-kovalenko** [comment]
When you will merge?

**Comment by knallcharge** [comment]
Friendly bump to keep this alive :)

**Comment by MatuzMark** [comment]
I tried to use with PHPStan version 2.1.1 but it failed with internal error.
I think first it must be fixed, because they made some internal changes, that should be updated by [the guide](https://github.com/phpstan/phpstan/blob/2.1.x/UPGRADING.md#upgrading-guide-for-extension-developers).

My code was

```php
<?php

function fun(): void
{
    try {
        $a = 10;
    } catch (\Throwable $th) {
        //throw $th;
    }
}
````

The internal error is:

$ vendor/bin/phpstan -v
Note: Using configuration file /var/www/phpstan-test/phpstan.neon.dist.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% < 1 sec

 -- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     Error
 -- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     Internal error: PHPStan\Analyser\RuleErrorTransformer::transform(): Argument #1 ($ruleError) must be of type PHPStan\Rules\RuleError, string given, called in phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php on line 119 while analysing file
     /var/www/phpstan-test/alma.php
     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.yaml:
     ## phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/RuleErrorTransformer.php(19)
     #0 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(119): PHPStan\Analyser\RuleErrorTransformer->transform()
     #1 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(572): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
     #2 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1323): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
     #3 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(450): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
     #4 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(594): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
     #5 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(398): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
     #6 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(162): PHPStan\Analyser\NodeScopeResolver->processNodes()
     #7 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(136): PHPStan\Analyser\FileAnalyser->analyseFile()
     #8 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111): PHPStan\Command\WorkerCommand::PHPStan\Command\{closure}()
     #9 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_2f712479f\Evenement\EventEmitter->emit()
     #10 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111): _PHPStan_2f712479f\Clue\React\NDJson\Decoder->handleData()
     #11 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_2f712479f\Evenement\EventEmitter->emit()
     #12 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111): _PHPStan_2f712479f\React\Stream\Util::_PHPStan_2f712479f\React\Stream\{closure}()
     #13 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(168): _PHPStan_2f712479f\Evenement\EventEmitter->emit()
     #14 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_2f712479f\React\Stream\DuplexResourceStream->handleData()
     #15 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_2f712479f\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
     #16 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(96): _PHPStan_2f712479f\React\EventLoop\StreamSelectLoop->run()
     #17 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute()
     #18 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_2f712479f\Symfony\Component\Console\Command\Command->run()
     #19 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_2f712479f\Symfony\Component\Console\Application->doRunCommand()
     #20 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_2f712479f\Symfony\Component\Console\Application->doRun()
     #21 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(114): _PHPStan_2f712479f\Symfony\Component\Console\Application->run()
     #22 phar:///var/www/phpstan-test/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(115): _PHPStan_2f712479f\{closure}()
     #23 /var/www/phpstan-test/vendor/phpstan/phpstan/phpstan(8): require('...')
     #24 /var/www/phpstan-test/vendor/bin/phpstan(119): include('...')
     #25 {main}
 -- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



 [ERROR] Found 1 error


⚠️  Result is incomplete because of severe errors. ⚠️
   Fix these errors first and then re-run PHPStan
   to get all reported errors.

Elapsed time: 1 second
Used memory: 48 MB

**Comment by homersimpsons** [comment]
Sorry for the delay, done with https://github.com/thecodingmachine/phpstan-strict-rules/pull/69

**Comment by knallcharge** [comment]
Using `composer require --dev thecodingmachine/phpstan-strict-rules` will add `"thecodingmachine/phpstan-strict-rules": "*"` to my composer.json but does not install the package ... ?

Composer shows
"./composer.json has been updated
Running composer update thecodingmachine/phpstan-strict-rules
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file"
adds the entry to composer.json, but that's it.

<img width="330" height="53" alt="Image" src="https://github.com/user-attachments/assets/38ceb06c-e41c-4b6c-ac31-d0d5450e9ed5" />

**Comment by homersimpsons** [comment]
@knallcharge that is rather strange. Could you share something to reproduce this ? (I'm not sure we can do anything on the package side)

1. Is the package referenced in your composer.lock?
2. What does a `composer why <package>` gives you?
3. What happens if you delete your composer.lock and run `composer install`?
4. Which tool is reporting whether the package is installed or not? Could its cache be stalled?

**Comment by knallcharge** [comment]
@homersimpsons Thanks for getting back!

1. The package shows in composer.json but not in composer.lock.
2. __root__ dev-develop requires (for development) thecodingmachine/phpstan-strict-rules (^2.0)
3. composer.lock gets regenerated, but the package is still not present. (In my vendor/thecodingmachine-folder I only have phpstan-safe-rule and safe).
4. The screenshot is from PhpStorm, showing composer.json. I don't know about its cache, but as the folder is missing in vendor, I guess PhpStorm is right.

I also just tried to delete the vendor-folder and download everything again - with the same result.

But you mentioning to check composer.lock lead me to the solution:
I found "`"provide": { "thecodingmachine/phpstan-strict-rules": "2.0" },`" in composer.lock which was created by the package "kcs/phpstan-strict-rules" which is a fork of the original package for phpstan 2 and which I forgot was installed.
Removing the kcs-package will show:
```
Lock file operations: 1 install, 0 updates, 1 removal
  - Removing kcs/phpstan-strict-rules (v2.1.0)
  - Locking thecodingmachine/phpstan-strict-rules (v2.0.0)
```
And now I have vendor/thecodingmachine/phpstan-strict-rules installed correctly and PhpStorm stopped complaining.

My bad, sorry for bothering.

**Comment by homersimpsons** [comment]
> My bad, sorry for bothering.

Appologies accepted. But no worries, I prefer a false-positive report than a missing-positive report. You took time to investigate this which is nice too.
